fs = 22050;
nBits = 16;
recobj = audiorecorder(fs, nBits, 1);
recordblocking(recobj, 1);
word = getaudiodata(recobj);
melSpectrogram(word, fs, 'NumBands', 16, 'FrequencyRange', [62.5,6e3]);
S = melSpectrogram(word, fs, 'NumBands', 16);
filename = "bird1-220";
writematrix(S, "spectrograms/b/" + filename + ".txt");
audiowrite("wavs/b/" + filename + ".wav", word, fs);